<a href="https://colab.research.google.com/github/khalilkhan1111/python_practice/blob/main/python_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Integers and Floats**

In [ ]:
def calculator(operator, num1, num2):
    try:
        if not (isinstance(num1, (int, float)) and isinstance(num2, (int, float))):
            raise ValueError("Invalid input. Numbers expected.")

        if operator == '+':
            result = num1 + num2
        elif operator == '-':
            result = num1 - num2
        elif operator == '*':
            result = num1 * num2
        elif operator == '/':
            if num2 == 0:
                raise ZeroDivisionError("Cannot divide by zero.")
            result = num1 / num2
        else:
            raise ValueError("Invalid operator.")

        return result
    except (ValueError, ZeroDivisionError) as e:
        return str(e)

try:
    num1 = float(input("Enter the first number: "))
    num2 = float(input("Enter the second number: "))
    operator = input("Enter the operator (+, -, *, /): ")

    result = calculator(operator, num1, num2)
    print("Result:", result)
except ValueError as ve:
    print("Error:", ve)
except ZeroDivisionError as zde:
    print("Error:", zde)

Enter the first number: 8.5
Enter the second number: 2
Enter the operator (+, -, *, /): -
Result: 6.5


**Introduction to Strings**

a string is a sequence of characters. It is a data type that represents text.

In [1]:
# Strings are immutable
a = "khalil!"
print(a)

khalil!


Length of a string

In [ ]:
len(a)

7

slicing technique


In [ ]:
#length is 0 to n-1
print(a[0:3])

kha


negative slicing


In [ ]:
(a[-5:-2])

'ali'

upper and lower case

In [ ]:
a.upper()


'KHALIL!'

In [ ]:
a.lower()

'khalil!'

replace

In [ ]:
print(a.replace( "khalil!","parveen!"))

parveen!


split

In [ ]:
print(a.split())

['khalil!']


Write a Python function to get a string made of 4
copies of the last two characters of a specified string (length must be at least 2).

In [ ]:
str1 = str(input())
def sub_str(str1):
    sub_str = str1[-2:]
    return sub_str * 4
print(sub_str(str1))

khalil
ilililil


Write a Python program to remove the nth index character from a nonempty string.

In [ ]:
strn = str(input())
n = int(input())
def remove_char(str, n):
     first_part = str[:n]
     last_part = str[n+1:]
     return first_part + last_part
print(remove_char(strn, n))

khalil
3
khail


Write a Python program to change a given string to a new string where the first and last chars have been exchanged.

In [ ]:
str1 = str(input())
def change_string(str1):
    return str1[-1:] + str1[1:-1] + str1[:1]
print(change_string(str1))

khalil
lhalik


**List**

 a list is a data structure that stores a collection of data items.

 it is mutable.

Given a list, write a Python program to swap first and last element of the list.

In [ ]:
a = [12, 35, 9, 56, 24]
def new_a(a) :
    return (a[-1:] + a[1:-1] + a[:1])
print(new_a(a))

[24, 35, 9, 56, 12]


Given two numbers, write a Python code to find the Maximum of these two numbers.

In [ ]:
#list are mutable
a = [3,4,10]
a = ["Apple", "apple","zebra"]
print(max(a))

zebra


Given two numbers, write a Python code to find the Minimum of these two numbers.

In [ ]:
a = [3,4,10]
a = ["Apple", "Zebra", "apple","zebra"]
print(min(a))

Apple


Check if an element exists in the list using the if-else statement

In [ ]:
test_list = [1, 6, 3, 5, 3, 4]
n = (int(input()))
if n in test_list :
    print(True)
else :
    print(False)

4
True


list in list

In [ ]:
myList=[[1, 2, 3, 4, 5], [12, 13, 23], [10, 20, 30], [11, 22, 33], [12, 24, 36]]
print(myList[3][2])

33


A list contains the average daily temperature(in degree Celsius) of
 a city over a particular week. Write a Python code to swap the highest and the lowest temperatures

In [ ]:
temperatures = [34, 40, 29, 33, 42, 37, 39 ]
max_temp = max(temperatures)
max_temp_index = temperatures.index(max_temp)
min_temp = min(temperatures)
min_temp_index = temperatures.index(min_temp)
temperatures[max_temp_index] = min_temp
temperatures[min_temp_index] = max_temp
print(temperatures)

[34, 40, 42, 33, 29, 37, 39]


removing nested

In [ ]:
tech_companies = ['Qualcomm','Google','Apple',['Nvidia','Cisco','Samsung']]
last = tech_companies[-1]
company = tech_companies[:3] + tech_companies[-1]
print(company)

['Qualcomm', 'Google', 'Apple', 'Nvidia', 'Cisco', 'Samsung']


type check


In [ ]:
print(type(tech_companies))

<class 'list'>


**Tuple**

a tuple is a data structure that is similar to a list, but it is immutable


In [ ]:
my_tuple = (1,'a',3)
my_tuple

(1, 'a', 3)

type check


In [ ]:
print(type(my_tuple))

<class 'tuple'>


indexing tuple

In [ ]:
my_tuple[2]

3

tuple slicing

In [ ]:
my_tuple[1:2]

('a',)

index

In [ ]:
a = (1,2,3,4,5,6,1,2,3,4)
a.index(4)

3

count

In [ ]:
a.count(2)

2

zip()

In [ ]:
city_list = ['Delhi','Patna','Cuttack','Guwahati']
river_list = ['Yamuna','Ganga','Mahanadi','Brahmaputra']

In [ ]:
zip(city_list, river_list)

In [ ]:
city_and_their_rivers = list(zip(city_list,river_list))

In [ ]:
city_and_their_rivers

[('Delhi', 'Yamuna'),
 ('Patna', 'Ganga'),
 ('Cuttack', 'Mahanadi'),
 ('Guwahati', 'Brahmaputra')]

**SET** - Sets are an unordered collection of unique elements. We can construct them by using the set() function.

Sets cannot have duplicates.

Sets are mutable just like lists.

You can create a non-empty set with curly braces by specifying elements separated by a comma.

In [2]:
set = {1,1,2,4,5,5,6,4,3}
set

{1, 2, 3, 4, 5, 6}

add()

In [8]:
set.add('a')
set

{1, 2, 3, 4, 5, 6, 'a'}

**update**

method helps to add multiple elements to a set

In [9]:
set.update([8, 7, 9])
set

{1, 2, 3, 4, 5, 6, 7, 8, 9, 'a'}

remove()

In [10]:
set.remove(9)
set

{1, 2, 3, 4, 5, 6, 7, 8, 'a'}

**union**

In [11]:
A = {1, 2, 3, 4, 5}
B = {4, 5, 6, 7, 8}
A.union(B)

{1, 2, 3, 4, 5, 6, 7, 8}

**intersection**

In [12]:
A.intersection(B)

{4, 5}

**Dictionaries**

A Python dictionary consists of a key and then an associated value. That value can be almost any Python object. So a dictionary object always has elements as key-value pairs

It is mutable

In [14]:
marvel_dict = {'Name':'Thor','Place':'Asgard','Weapon' : 'Hammer', 1:2, 3 : 'power', 'alibies' : ['Ironman','Captain America'], 'abc' : {1:2, 4:5}}
marvel_dict['Name']

'Thor'

**Keys**

In [15]:
marvel_dict.keys()

dict_keys(['Name', 'Place', 'Weapon', 1, 3, 'alibies', 'abc'])

place

In [16]:
marvel_dict.get('Place')

'Asgard'

index

In [17]:
employee_dict = {'Name':'Sanket','Skills':['Python','Machine Learning','Deep Learning'],'Band':6.0,'Promotion Year':[2016,2018,2020]}
employee_dict['Skills'][0]

'Python'

upper

In [18]:
employee_dict['Skills'][0].upper()

'PYTHON'

lower

In [20]:
employee_dict['Skills'][0].lower()

'python'

update

In [22]:
employee_dict.update({'Salary':'2,000,000'})

zip

In [23]:
country_list = ['India','Australia','United States','England']
city_list = ['New Delhi', 'Canberra' , 'Washington DC','London']

In [24]:
country_city_list = list(zip(country_list,city_list))

In [25]:
country_city_list

[('India', 'New Delhi'),
 ('Australia', 'Canberra'),
 ('United States', 'Washington DC'),
 ('England', 'London')]

**Numpy**

NumPy is a Python package. It stands for 'Numerical Python'. It is a library consisting of multidimensional array objects and a collection of routines for processing of array. The NumPy package is the workhorse of data analysis, machine learning, and scientific computing in the python ecosystem. It vastly simplifies manipulating and crunching vectors and matrices. Some of python’s leading package rely on NumPy as a fundamental piece of their infrastructure (examples include scikit-learn, SciPy, pandas, and tensorflow). Beyond the ability to slice and dice numeric data, mastering numpy will give you an edge when dealing and debugging with advanced usecases in these libraries.

In [26]:
import numpy as np

1D array

In [27]:
prime_array = np.array([2,3,5,7,11])
print(prime_array)

[ 2  3  5  7 11]


2D array

In [28]:
array = np.array([[1,2],[3,4]])
array

array([[1, 2],
       [3, 4]])

3D array

In [29]:
D_array = np.array([[[1,2],[3,4]], [[5,6],[7,8]]])
D_array

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

Indexing and Slicing Arrays
Contents of ndarray object can be accessed and modified by indexing or slicing.

In [31]:
a = np.arange(10)
a[5]

5

In [32]:
# slice items between indexes
a = np.arange(10)
a[2:5]

array([2, 3, 4])

In [33]:
# retrieving elements from a 2-D array
a = np.array([[1,2,3],[4,5,6]])
print(a[1,2])

6


In [34]:
# For 3-D array slicing the format is array[index,row,column]
a = np.array([[[1,2],[3,4],[5,6]],
             [[7,8],[9,10],[11,12]],
             [[13,14],[15,16],[17,18]]])
print(a)
print(a[0:2])
print(a[0:2,1:,1:])

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[[[ 4]
  [ 6]]

 [[10]
  [12]]]


np.transpose()

Transpose is defined as an operator which flips a matrix over its diagonal; that is, it switches the row and column indices of the matrix A by producing another matrix

In [35]:
arravali = np.array(np.random.randint(10,45,(8,2)))
print(f"The defined array is \n{arravali}")
print(f" \n The shape of the array is {arravali.shape}")

The defined array is 
[[11 16]
 [17 16]
 [29 34]
 [17 11]
 [40 43]
 [12 35]
 [33 17]
 [22 10]]
 
 The shape of the array is (8, 2)


In [36]:
# Storing the transpose in another matrix object
nilgiri =np.transpose(arravali)
print(f" The transpose of the array is \n{nilgiri}")
print(f" \n The shape of the array is {nilgiri.shape}")

 The transpose of the array is 
[[11 17 29 17 40 12 33 22]
 [16 16 34 11 43 35 17 10]]
 
 The shape of the array is (2, 8)


np.reshape(shape)

Gives a new shape to an array without changing its data.

In [37]:
random_3D= np.array(np.random.randint(10,45,(3,6,2)))
print(f"The defined array is \n{random_3D}")
print(f" \n The shape of the array is {random_3D.shape}")

The defined array is 
[[[17 11]
  [42 35]
  [33 31]
  [17 39]
  [37 13]
  [40 20]]

 [[43 42]
  [25 25]
  [28 28]
  [28 23]
  [44 39]
  [36 13]]

 [[25 24]
  [16 38]
  [20 13]
  [27 17]
  [42 32]
  [31 18]]]
 
 The shape of the array is (3, 6, 2)


In [38]:
new_shape = (2,-1,6)
reshaped_random_3D = np.reshape(random_3D,new_shape)
print(f"The reshaped array is \n{reshaped_random_3D}")
print(f" \n The shape of the array is {reshaped_random_3D.shape}")

The reshaped array is 
[[[17 11 42 35 33 31]
  [17 39 37 13 40 20]
  [43 42 25 25 28 28]]

 [[28 23 44 39 36 13]
  [25 24 16 38 20 13]
  [27 17 42 32 31 18]]]
 
 The shape of the array is (2, 3, 6)


np.flatten()

In [39]:
random_3D.flatten()

array([17, 11, 42, 35, 33, 31, 17, 39, 37, 13, 40, 20, 43, 42, 25, 25, 28,
       28, 28, 23, 44, 39, 36, 13, 25, 24, 16, 38, 20, 13, 27, 17, 42, 32,
       31, 18])

insert

In [40]:
a = np.random.randint(10,20,(2,3,4))
np.insert(a,1,100,axis=0)

array([[[ 14,  15,  15,  10],
        [ 13,  12,  17,  10],
        [ 13,  16,  18,  12]],

       [[100, 100, 100, 100],
        [100, 100, 100, 100],
        [100, 100, 100, 100]],

       [[ 12,  17,  19,  19],
        [ 12,  18,  14,  11],
        [ 15,  14,  10,  13]]])

np.append

In [41]:
np.append(a, 50)

array([14, 15, 15, 10, 13, 12, 17, 10, 13, 16, 18, 12, 12, 17, 19, 19, 12,
       18, 14, 11, 15, 14, 10, 13, 50])

np.delete

In [42]:
# Delete along Axis=0
np.delete(a,(0),axis = 0)

array([[[12, 17, 19, 19],
        [12, 18, 14, 11],
        [15, 14, 10, 13]]])

unique

In [43]:
np.unique(a)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

**Pandas**

Pandas is designed to make it easier to work with structured data. Most of the analyses you might perform will likely involve using tabular data, e.g., from .csv files or relational databases (e.g., SQL). The DataFrame object in pandas is "a two-dimensional tabular, column-oriented data structure with both row and column labels."

In [44]:
import pandas as pd
import numpy as np

There are two central concepts which you should know about:

Series : A series is essentially a column

Data Frame : A DataFrame is a two-dimensional data structure, i.e., data is aligned in a tabular fashion in rows and columns. Pandas DataFrame consists of three principal components, the data, rows, and columns.

In [45]:
# Our first series
number_series = pd.Series([2, 3, 5, 6, 8])
print(number_series)

0    2
1    3
2    5
3    6
4    8
dtype: int64


In [46]:
# Same series but with different indices
number_series = pd.Series([2, 3, 5, 6, 8],index=['a', 'b', 'd','e','f'],name='Number')
print(number_series)

a    2
b    3
d    5
e    6
f    8
Name: Number, dtype: int64


In [47]:
some_2D_array = np.random.randint(4, 6,(3,4))
first_dataframe = pd.DataFrame(some_2D_array , columns=['Akshay','Devashish','Divy','Monika'])
first_dataframe

Akshay  Devashish  Divy  Monika
0       5          5     5       4
1       5          4     5       4
2       4          4     4       4

list of list

In [48]:
# Initialize list of lists
list_of_lists = [['Amar', 10], ['Akbar', 15], ['Anthony', 14]]
df = pd.DataFrame(list_of_lists, columns = ['Name', 'Age'])
df

Name  Age
0     Amar   10
1    Akbar   15
2  Anthony   14

dictionary

In [49]:
# Store the data in a dictionary
employee_dict = {'Employee Name':['Rajeev', 'Sumit', 'Aviral'], 'Income':[200000, 140000, 90000]}
employee_df = pd.DataFrame(employee_dict)
employee_df

Employee Name  Income
0        Rajeev  200000
1         Sumit  140000
2        Aviral   90000

head()

By default it prints the first 5 rows

In [50]:
our_array = np.random.randn(100, 5)
df = pd.DataFrame(our_array, columns=['A','B','C','D','E'])
df

A         B         C         D         E
0  -0.159769 -0.402866 -1.926161  0.271030  0.616196
1  -1.610083  0.008315 -0.831867 -0.964520  0.584983
2   0.001967 -0.339341 -1.544576 -0.987981  0.028578
3  -0.455836 -0.552677 -1.188060  1.139448  0.959891
4  -0.802088  0.713720  0.100928 -1.040813  1.801073
..       ...       ...       ...       ...       ...
95  0.670077 -1.206235 -0.485421  0.461012  0.308741
96  0.380948 -1.944076  2.358563 -0.351297 -0.062778
97  2.855458  0.922483  1.627456 -2.549957 -2.467681
98 -0.596201  0.878930 -0.560671 -2.170410 -0.149498
99 -3.034835  1.708374 -1.633910 -1.004741 -2.036561

[100 rows x 5 columns]

In [51]:
df.head()

A         B         C         D         E
0 -0.159769 -0.402866 -1.926161  0.271030  0.616196
1 -1.610083  0.008315 -0.831867 -0.964520  0.584983
2  0.001967 -0.339341 -1.544576 -0.987981  0.028578
3 -0.455836 -0.552677 -1.188060  1.139448  0.959891
4 -0.802088  0.713720  0.100928 -1.040813  1.801073

tail()

By default it prints the last 5 rows

In [52]:
df.tail()

A         B         C         D         E
95  0.670077 -1.206235 -0.485421  0.461012  0.308741
96  0.380948 -1.944076  2.358563 -0.351297 -0.062778
97  2.855458  0.922483  1.627456 -2.549957 -2.467681
98 -0.596201  0.878930 -0.560671 -2.170410 -0.149498
99 -3.034835  1.708374 -1.633910 -1.004741 -2.036561

columns

In [53]:
list(df.columns)

['A', 'B', 'C', 'D', 'E']

info()

Prints the basic information about our dataframe

In [54]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   A       100 non-null    float64
 1   B       100 non-null    float64
 2   C       100 non-null    float64
 3   D       100 non-null    float64
 4   E       100 non-null    float64
dtypes: float64(5)
memory usage: 4.0 KB


rename()

In [56]:
df.rename(columns ={'A':'D'}, inplace = True)
df

D         B         C         D         E
0  -0.159769 -0.402866 -1.926161  0.271030  0.616196
1  -1.610083  0.008315 -0.831867 -0.964520  0.584983
2   0.001967 -0.339341 -1.544576 -0.987981  0.028578
3  -0.455836 -0.552677 -1.188060  1.139448  0.959891
4  -0.802088  0.713720  0.100928 -1.040813  1.801073
..       ...       ...       ...       ...       ...
95  0.670077 -1.206235 -0.485421  0.461012  0.308741
96  0.380948 -1.944076  2.358563 -0.351297 -0.062778
97  2.855458  0.922483  1.627456 -2.549957 -2.467681
98 -0.596201  0.878930 -0.560671 -2.170410 -0.149498
99 -3.034835  1.708374 -1.633910 -1.004741 -2.036561

[100 rows x 5 columns]